service_url:
  payment: http://192.168.1.3:8082

api_routes:
  initiate-payment: /initiate-payment
  get-available-payment-methods: /get-available-payment-methods
  rollback-payment: /rollback-payment
